spring:
  profiles:
    active: local
    include: mail, my
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
      # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

file:
  dir: /Users/bagchanbyeong/Documents/FIle/fileRepository
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6